unit TestUntValidacao;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Windows, Forms, Dialogs, Controls, Classes, SysUtils, UntValidacao,
  Variants, Graphics, Messages, StdCtrls;

type
  // Test methods for class TForm1

  TestTForm1 = class(TTestCase)
  strict private
    FForm1: TForm1;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestRemoveAspas;
  end;

implementation

procedure TestTForm1.SetUp;
begin
  FForm1 := TForm1.Create(Application);
end;

procedure TestTForm1.TearDown;
begin
  FForm1.Free;
  FForm1 := nil;
end;

procedure TestTForm1.TestRemoveAspas;
var
  texto: string;
  textoEsperado: string;
begin
  // TODO: Setup method call parameters
  texto := RemoveAspas('D''água');
  textoEsperado := 'Dágua';

  // TODO: Validate method results
  Assert(texto = textoEsperado);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTForm1.Suite);
end.

