-- select: SELECT <lista campos> FROM <lista tabelas> WHERE <concições>

-- RECUPERAR TODOS OS CLIENTES

select * from cliente;

-- RECUPERAR TODOS OS CLIENTES COM LIMITE DE CRÉDITO ACIMA DE 1000

SELECT * FROM cliente WHERE CLIENTE.limitecredito > 1000;

-- RECUPERAR TODOS OS CLIENTES COM DATA DE NASCIMENTO APÓS 1980

SELECT * FROM cliente WHERE CLIENTE.datanascimento >= '01.01.1981';

-- RECUPERAR O NOME E A DATA DE NASCIMENTO CLIENTES NASCIDOS NO ANO DE 1983

SELECT NOME, DATANASCIMENTO FROM cliente WHERE cliente.datanascimento >= '01.01.1983' AND cliente.datanascimento <= '31.12.1983';

SELECT NOME, DATANASCIMENTO FROM cliente WHERE cliente.datanascimento BETWEEN '01.01.1983' AND '31.12.1983'; --BETWEEN SIGNIFICA ESTA ENTRE OS VALORES PASSADOS(INCLUSIVE).

SELECT NOME, DATANASCIMENTO FROM cliente WHERE EXTRACT(YEAR FROM DATANASCIMENTO) = 1983;-- FUNÇÃO QUE EXTRAI O COMPONENTE DA DATA.


-- RECUPERAR TODOS OS CLIENTES COM LIMITE DE CRÉDITO ACIMA DE 2000 E NASCIDOS ANTES DE 1982

SELECT * FROM cliente WHERE cliente.limitecredito > 2000 AND EXTRACT(YEAR FROM DATANASCIMENTO) < 1982;

-- RECUPERAR OS NOMES DOS CLIENTES CUJO NOME TERMINE COM "O"

SELECT NOME FROM cliente WHERE CLIENTE.nome LIKE '%O';-- O LIKE ENCONTRA CARACTERES DENTRO UMA STRING. O PORCENTO INDICA QUAISQUER CARACTERES.
                                                      -- SE COLOCADO ANTES A PESQUISA SERÁ NOS CARACTERES FINAIS.

-- RECUPERAR OS NOMES DOS CLIENTES CUJO NOME COMECE COM "C"

SELECT NOME FROM cliente WHERE cliente.nome LIKE 'C%';

-- RECUPERAR OS NOMES DOS CLIENTES CUJO NOME CONTENHA A LETRA "A"

SELECT NOME FROM CLIENTE WHERE cliente.nome LIKE '%A%';
